### ISSUE TITLE
Shooting an arrow at an item frame crashes the game

### ISSUE THREAD

**Issue by Rufflikerex** [Flemmli97/Flan#27] opened 2021-01-01 22:09 UTC
#### Issue (The better the description the better i can solve the issue):
Shooting an arrow at an item frame carrying a map crashes the server if it occurs within a protected claim that the shooter does not own. Usually causes the server to freeze until it goes over the max tick speed limit.

#### Steps to reproduce:
1. Get someone to claim a chunk of land, and have them place an item frame with a map in that claim.
2. Load a crossbow with an arrow, have a player that doesn't own that claim shoot the item frame with an arrow.
3. Watch as the server dies.

I suspect it may be an unexpected case of entity modification/destruction that was overlooked. Maybe destroying claimed property using other indirect means could unearth more possible issues.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.16.4
- Fabric: 0.6.1.51
- Flan: 1.16.2-1.2.1

#### Other Mods (If you think it might be cause of an incompatibility):
None

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE): 
No log is generated, rather the server freezes until it crashes due to max-tick-time being exceeded.

**Comment by Flemmli97** [comment] 2021-01-21 16:57
i cant reproduce it. what other mods do you have on the server? and also update fabric

**Comment by ghost** [comment] 2021-07-14 12:57
obsolete fabric api

**Comment by Flemmli97** [comment] 2021-07-30 17:53
closing dead issues

**Closed by Flemmli97** 2021-07-30 17:53 UTC
