### ISSUE TITLE
More Bug's.

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#240] opened 2023-05-28 19:28 UTC
### Modloader

Forge

### Minecraft version

1.19.2

### Modloader version

Forge

### Mod version

flan-1.19.2-1.8.4-forge

### Description

1. Boats during movements break frames, pictures in a foreign region.
2. Ender Crystals explode players in a foreign region if you place an Ender Crystal close to the region. Ender crystals also explode frames, paintings, armor racks in a foreign region.
3. Explosions and damage from arrows go through portals to hell, even if they are in a foreign region, you can go into someone else's portal and shoot or explode right from hell, the explosion will kill the player in the ordinary world through his portal.

### Steps to reproduce

1. Boats during movements break frames, pictures in a foreign region.
2. Ender Crystals explode players in a foreign region if you place an Ender Crystal close to the region. Ender crystals also explode frames, paintings, armor racks in a foreign region.
3. Explosions and damage from arrows go through portals to hell, even if they are in a foreign region, you can go into someone else's portal and shoot or explode right from hell, the explosion will kill the player in the ordinary world through his portal.

### Logs

no crash logs.

**Comment by MrJorman** [comment] 2023-06-06 15:58
In region can explode itemframe, armor stands - creeper and other explodes (example end crystal)

**Comment by Flemmli97** [comment] 2023-06-08 22:40
2. duplicate of #221
3. duplicate of #222

**Comment by Flemmli97** [comment] 2023-07-10 15:18
1. duplicate of #231

**Closed as completed by Flemmli97** 2023-07-10 15:18 UTC
