### ISSUE TITLE
[BUG] Flan 1.19.2 Fabric - Ender Crystals kill players in private

### ISSUE THREAD

**Issue by MrJorman** [Flemmli97/Flan#221] opened 2023-01-20 20:03 UTC
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

Fabric

### Mod version

flan-1.19.2-1.8.3-fabric.jar

### Description

PVP between players is disabled in a foreign region. But if you put the ender crystal close, it will kill the players in private.
![image](https://user-images.githubusercontent.com/55187962/213795109-e50a91be-9cb0-4405-ac7b-7d155120aa10.png)

### Steps to reproduce

See screenshot.

### Mods that might affect the issue

Flan mod + Vanilla

### Logs

No crash reports.

**Comment by Flemmli97** [comment] 2023-03-10 20:52
duplicate of #181

**Closed as completed by Flemmli97** 2023-03-10 20:52 UTC
Labels: wontfix
