### ISSUE TITLE
Mobs still not spawn

### ISSUE THREAD

**Issue by Jan3004** [Flemmli97/Flan#67] opened 2021-06-21 13:20 UTC
Hello. In the latest version 1.17(fabric) Flan: 1.5.1, mobs are still not spawning in the entire map.

**Comment by Jan3004** [comment] 2021-06-21 13:31
i fixed it. But they spawn weird

**Comment by Jan3004** [comment] 2021-06-21 13:32
In some places they spawn and in some they don't

**Comment by ashfalladruid** [comment] 2021-07-04 00:14
can you  explain to me how you did this i am haveing the same problem

**Comment by MaxBr5** [comment] 2021-07-06 20:01
<pre>I think animals, birds and fish only
spawn in claimed land but I don't know, I
don't use any land claiming mods on any
of my multiplayer worlds.</pre>

**Comment by MaxBr5** [comment] 2021-07-06 20:02
<pre>I hope this may give you a clue</pre>

**Comment by bbbower** [comment] 2021-07-19 22:05
Having the same issue, toggling mobspawn permissions does not affect it, nothing will spawn in claim area.

On top of that, if I unclaim the area or delete the claim, mobs will continue to not spawn in the area i had originally claimed indefinitely.   This includes natural spawns, and even moving a spawner to the area, its like it's perma saved to the key file.

**Comment by MaxBr5** [comment] 2021-07-20 18:08
<pre>I think you may need to delete flan and just get by.</pre>

**Comment by Flemmli97** [comment] 2021-07-22 12:25
config? version? anything? cause it works fine on my end.
also i dont do anything with mobspawner so that is not on me

**Comment by AetheriMC** [comment] 2021-11-23 23:34
I'll add to this as I've had the same issue on our server. It took a while to narrow down and confirm that the problem was FLAN, but I can now say 100%, that the issue is with this mod.

Minecraft v1.16.5
Forge v36.2.0
FLAN v1.6.2

Issue: Modifying the config causes hostile mobs to stop spawning in the world. Specifically, with a clean config the mod works perfectly, but after updating the global default permissions, claiming items, starting blocks, and max claim blocks, the hostile mobs quit appearing.

I have no idea if the issue is fixed in 1.6.3, but this is how I'm able to reliably replicate the bug.

**Comment by Flemmli97** [comment] 2021-12-05 10:06
i mean if you changed the config then it might be good to post the changed config file here (via a paste site)

**Comment by Flemmli97** [comment] 2022-02-18 00:05
reopen if issue persist

**Closed as completed by Flemmli97** 2022-02-18 00:05 UTC
