### ISSUE TITLE
Not able to carry out command in command block and datapack

### ISSUE THREAD

**Issue by Bluyidark** [Flemmli97/Flan#195] opened 2022-11-06 11:50 UTC
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

Fabric Loader 0.14.9 1.19.2

### Mod version

flan-1.19-1.8.1.1-fabric

### Description

Flan command not working when put in command block and datapack, as it didn't do anything after the command block is activated.

### Steps to reproduce

1. Put a command block and type in "/flan giveClaimBlocks @p 100"
2. Put a button on top and activate it

### Logs

No logs available

**Comment by Flemmli97** [comment] 2022-11-15 17:28
cant reproduce. i did exactly what you said and it worked without problems

**Comment by Bluyidark** [comment] 2022-12-31 04:41
Hi, sorry for the late reply! So I did a lot more testing, found out that the command /flan giveClaimBlocks @p 100 can just do fine. Still, when I change @p to @s it will not work anymore, so I wonder if this is intentional.

**Comment by Bluyidark** [comment] 2023-01-05 06:50
Also another update! I'm currently testing it in a server, as the command (for example: /flan giveClaimBlocks @p 100 ) can't be carried out in command block, signs and datapack now, only the operators are allowed to execute the command by typing it in chat only.

**Comment by Flemmli97** [comment] 2023-03-10 20:32
yes. because @s refers to the one using the command. and in this case the command block.

**Comment by Flemmli97** [comment] 2023-07-09 21:50
closing since solved

**Closed as completed by Flemmli97** 2023-07-09 21:50 UTC
